#!/bin/sh

serverPath=`pwd`

if [ $# -eq 1 ]
  then
    eval serverPath=$1
fi

echo "Starting server at:" $serverPath
echo

config="server.document-root = \"${serverPath}\"\n"
config="${config}server.port = 3000\n"
config="${config}"'mimetype.assign = (".html" => "text/html", ".css" => "text/css", ".txt" => "text/plain",".jpg" => "image/jpeg", ".png" => "image/png", ".js" => "application/javascript", ".json" => "application/json")'

echo $config > lighttpd.config

lighttpd -t -f lighttpd.config
lighttpd -D -f lighttpd.config


