#!/bin/sh

serverPath=`pwd`

echo "Starting server at:" $serverPath

config="server.document-root = \"${serverPath}\"\n"
config="${config}server.port = 3000\n"
config="${config}"'mimetype.assign = (".html" => "text/html", ".txt" => "text/plain",".jpg" => "image/jpeg", ".png" => "image/png", ".js" => "application/javascript")'

echo $config > lighttpd.config

lighttpd -t -f lighttpd.config
lighttpd -D -f lighttpd.config


